#!/usr/bin/env sh

set -e

# eg: ./scripts/build adder
EXAMPLE=$1

rm -rf target
mkdir target

echo "embed"
wasm-tools component embed \
  $EXAMPLE.wit $EXAMPLE.wat \
  --world root \
  --output target/$EXAMPLE.embed.wasm

echo "new"
wasm-tools component new \
  target/$EXAMPLE.embed.wasm \
  --output target/$EXAMPLE.component.wasm
